package org.example.Entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "operational_expenses")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class OperationalExpenses {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "expense_reference", unique = true, length = 8)
    private String expenseReference;  // Universal expense ID (e.g., EX250001)
    
    @NotNull(message = "Expense category is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private ExpenseCategory category;
    
    @NotBlank(message = "Expense name is required")
    @Size(min = 3, max = 255, message = "Expense name must be between 3 and 255 characters")
    @Column(name = "expense_name", nullable = false)
    private String expenseName;
    
    @NotBlank(message = "Description is required")
    @Size(min = 3, max = 1000, message = "Description must be between 3 and 1000 characters")
    @Column(name = "description", nullable = false)
    private String description;
    
    @NotNull(message = "Amount is required")
    @DecimalMin(value = "0.01", message = "Amount must be greater than 0")
    @Column(name = "amount", nullable = false)
    private Double amount;
    
    @NotNull(message = "Expense date is required")
    @Column(name = "expense_date", nullable = false)
    private LocalDate expenseDate;
    
    @Size(max = 100, message = "Payment method must not exceed 100 characters")
    @Column(name = "payment_method")
    private String paymentMethod;
    
    @Size(max = 255, message = "Vendor name must not exceed 255 characters")
    @Column(name = "vendor")
    private String vendor;
    
    @Column(name = "reference_number")
    private String referenceNumber;
    
    @Column(name = "receipt_url")
    private String receiptUrl;
    
    @Column(name = "status")
    private String status; // pending, paid, cancelled
    
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;
    
    // Approval fields
    @Column(name = "approval_status", nullable = false)
    private String approvalStatus; // PENDING, APPROVED, REJECTED
    
    @Column(name = "approval_comment", columnDefinition = "TEXT")
    private String approvalComment;
    
    @Column(name = "approved_at")
    private LocalDateTime approvedAt;
    
    // Payment fields
    @Column(name = "payment_status", nullable = false)
    private String paymentStatus; // UNPAID, PAID
    
    @Column(name = "paid_at")
    private LocalDateTime paidAt;
    
    @Column(name = "requested_by_user_id")
    private Long requestedByUserId;
    
    @Column(name = "approved_by_user_id")
    private Long approvedByUserId;
    
    @Column(name = "paid_by_user_id")
    private Long paidByUserId;
    
    @CreatedBy
    @Column(name = "created_by", updatable = false)
    private String createdBy;
    
    @LastModifiedBy
    @Column(name = "last_modified_by")
    private String lastModifiedBy;
    
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    
    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        // DO NOT generate expenseReference here - it's generated by the service layer
        // using UniqueIdGenerator to ensure proper 8-character format (EX######)
        if (status == null || status.isEmpty()) {
            status = "pending";
        }
        if (approvalStatus == null || approvalStatus.isEmpty()) {
            approvalStatus = "PENDING";
        }
        if (paymentStatus == null || paymentStatus.isEmpty()) {
            paymentStatus = "UNPAID";
        }
        // Note: requestedBy will be set by the service layer using UserAttributionService
        // This ensures we get the full name from JWT token, not just username
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
