package org.example.Controllers;

import org.example.DTO.LoanProductResponse;
import org.example.Entities.LoanProduct;
import org.example.Services.LoanProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/loan-products")
@CrossOrigin(origins = "*")
public class LoanProductController {

    private final LoanProductService loanProductService;

    @Autowired
    public LoanProductController(LoanProductService loanProductService) {
        this.loanProductService = loanProductService;
    }

    // Get all loan products
    @GetMapping
    public ResponseEntity<List<LoanProductResponse>> getAllLoanProducts(
            @RequestParam(defaultValue = "true") boolean activeOnly) {
        
        List<LoanProduct> products = loanProductService.getAllLoanProducts(activeOnly);
        
        List<LoanProductResponse> response = products.stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
        
        return ResponseEntity.ok(response);
    }

    // Get loan product by ID
    @GetMapping("/{id}")
    public ResponseEntity<LoanProductResponse> getLoanProductById(@PathVariable Long id) {
        return loanProductService.getLoanProductById(id)
                .map(this::convertToResponse)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    // Get loan product by code
    @GetMapping("/code/{productCode}")
    public ResponseEntity<LoanProductResponse> getLoanProductByCode(@PathVariable String productCode) {
        return loanProductService.getLoanProductByCode(productCode)
                .map(this::convertToResponse)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    // Create new loan product with auto-generated code and auto-assigned creator user ID
    @PostMapping("/addLoanProduct")
    public ResponseEntity<LoanProductResponse> addLoanProduct(@RequestBody LoanProduct loanProduct) {
        try {
            // ProductCode and createdByUserId will be auto-generated by the service
            // Remove any values sent from frontend (will be ignored)
            loanProduct.setProductCode(null);
            loanProduct.setCreatedByUserId(null);  // Always set from authenticated user's JWT token
            
            LoanProduct savedProduct = loanProductService.createLoanProduct(loanProduct);
            return ResponseEntity.status(HttpStatus.CREATED)
                    .body(convertToResponse(savedProduct));
        } catch (Exception e) {
            e.printStackTrace(); // Log the error for debugging
            return ResponseEntity.badRequest().build();
        }
    }

    // Update loan product (productCode cannot be changed)
    @PutMapping("/{id}")
    public ResponseEntity<LoanProductResponse> updateLoanProduct(
            @PathVariable Long id, 
            @RequestBody LoanProduct loanProduct) {
        
        try {
            LoanProduct updatedProduct = loanProductService.updateLoanProduct(id, loanProduct);
            return ResponseEntity.ok(convertToResponse(updatedProduct));
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build();
        }
    }

    // Deactivate loan product (soft delete)
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deactivateLoanProduct(@PathVariable Long id) {
        try {
            loanProductService.deactivateLoanProduct(id);
            return ResponseEntity.ok().build();
        } catch (Exception e) {
            return ResponseEntity.notFound().build();
        }
    }

    // Search products by name
    @GetMapping("/search")
    public ResponseEntity<List<LoanProductResponse>> searchLoanProducts(@RequestParam String name) {
        List<LoanProduct> products = loanProductService.searchLoanProductsByName(name);
        List<LoanProductResponse> response = products.stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
        
        return ResponseEntity.ok(response);
    }

    // Get products suitable for a specific loan amount
    @GetMapping("/suitable-for-amount")
    public ResponseEntity<List<LoanProductResponse>> getProductsForAmount(@RequestParam double amount) {
        List<LoanProduct> products = loanProductService.getProductsForAmount(amount);
        List<LoanProductResponse> response = products.stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
        
        return ResponseEntity.ok(response);
    }

    // Get products that require guarantor
    @GetMapping("/requiring-guarantor")
    public ResponseEntity<List<LoanProductResponse>> getProductsRequiringGuarantor() {
        List<LoanProduct> products = loanProductService.getProductsRequiringGuarantor();
        List<LoanProductResponse> response = products.stream()
                .map(this::convertToResponse)
                .collect(Collectors.toList());
        
        return ResponseEntity.ok(response);
    }

    // Convert entity to response DTO
    private LoanProductResponse convertToResponse(LoanProduct product) {
        return LoanProductResponse.builder()
                .id(product.getId())
                .productName(product.getProductName())
                .productCode(product.getProductCode())
                .description(product.getDescription())
                .displayName(product.getDisplayName())
                .defaultInterestRate(product.getDefaultInterestRate())
                .interestMethod(product.getInterestMethod())
                .interestType(product.getInterestType())
                .ratePer(product.getRatePer())
                .minDuration(product.getMinDuration())
                .maxDuration(product.getMaxDuration())
                .defaultDuration(product.getDefaultDuration())
                .durationUnit(product.getDurationUnit())
                .minAmount(product.getMinAmount())
                .maxAmount(product.getMaxAmount())
                .allowedRepaymentFrequencies(product.getAllowedRepaymentFrequenciesArray())
                .defaultRepaymentFrequency(product.getDefaultRepaymentFrequency())
                .processingFeeType(product.getProcessingFeeType())
                .processingFeeValue(product.getProcessingFeeValue())
                .lateFee(product.getLateFee())
                .defaultFee(product.getDefaultFee())
                .defaultGracePeriodDays(product.getDefaultGracePeriodDays())
                .registrationFeeTiers(product.getRegistrationFeeTiers())
                .penaltyRate(product.getPenaltyRate())
                .requiresGuarantor(product.isRequiresGuarantor())
                .requiresCollateral(product.isRequiresCollateral())
                .active(product.isActive())
                .createdAt(product.getCreatedAt())
                .updatedAt(product.getUpdatedAt())
                .createdByUserId(product.getCreatedByUserId())
                .build();
    }
}